compressionLevel: mixed

enableGlobalCache: false

enableTelemetry: false

logFilters:
  - code: YN0002
    level: info
  - code: YN0060
    level: info
  - code: YN0006
    level: info
  - code: YN0076
    level: info

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.0.2.cjs
